version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "3181:3181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "10092:10092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:3181
      KAFKA_ADVERTISED_PORT: "10092"
  subreddit-queues:
    links:
      - kafka
    container_name: subreddit-queues
    build: .
    restart: always
    hostname: subreddit-queues

